
version: "3"
services:
  riot-games-db:
    image: postgres:15.1
    networks:
      - riot-games-network
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/data/postgres
    env_file:
      - docker.env

  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - riot-games-network
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env

  riot-games-api:
    image: riot-games-api
    build:
      context: .
      # noinspection ComposeUnknownKeys
      target: install-dependencies
    command: npm run start:dev
    volumes:
      - ./src:/user/src/app/src
    env_file:
      - .docker.node.env
    ports:
      - "3000:3000"
      - "9229:9229"
    links:
      - riot-games-db
    depends_on:
      - riot-games-db
    networks:
      - riot-games-network

networks:
  riot-games-network:
    driver: bridge